---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authentications":
    post:
      summary: create authentication
      parameters:
      - name: credentials
        in: query
        schema:
          type: object
          properties:
            authentication:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
          required:
          - authentication
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  user_email:
                    type: string
                  token:
                    type: string
                required:
                - user_id
                - user_email
                - token
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/signup":
    post:
      summary: create signup
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                data:
                  "$ref": "#/components/schemas/user"
        '422':
          description: unprocessable
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/jsonapi_error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
                      enum:
                      - user
                    attributes:
                      type: object
                      properties:
                        email:
                          type: string
                        password:
                          type: string
                        password_confirmation:
                          type: string
                      required:
                      - email
                      - password
                      - password_confirmation
                  required:
                  - attributes
  "/users":
    get:
      summary: list users
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/user"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/login_prompt"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3189
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authentication
      description: Bearer token
      in: header
  schemas:
    jsonapi_error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              source:
                type: object
                properties:
                  pointer:
                    type: string
              title:
                type: string
              detail:
                type: string
              code:
                type: string
            required:
            - status
      required:
      - errors
    user:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
          - user
        attributes:
          type: object
          properties:
            email:
              type: string
          required:
          - email
      required:
      - attributes
    login_prompt:
      type: object
      properties:
        message:
          type: string
          enum:
          - Please log in
